name: Main CI
run-name: ${{ github.actor }} is testing.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.12.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-verstion: ${{ matrix.node }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci